### ISSUE TITLE
240x320 image cannot displaying

### ISSUE THREAD

**Issue by sangjela** [pimoroni/st7789-python#15]
https://github.com/pimoroni/st7789-python/blob/dada81e32d22f9a619dbdc7dbe39432db781e233/library/ST7789/__init__.py#L350

    result[..., [0]] = np.add(np.bitwise_and(pb[..., [0]], 0xF8), np.right_shift(pb[..., [1]], 5))
ValueError: shape mismatch: value array of shape (240,320,1) could not be broadcast to indexing result of shape (1,320,240)

in test np shape, 
 np.array return (320, 240, 3) from image 240x320, so shape mismatch occur?

I use self.width, self.height temporately for bug fix, not self._width, self._height....

I use next initial code.
.ST7789( ..., width=320, height=240 ...) //it have rotation 90 by default

**Comment by slabua** [comment]
@sangjela 
This is the [proper fix ](https://github.com/pimoroni/st7789-python/compare/master...slabua:feature/240x135-lcd?expand=1#diff-899346a6ee09030bb9563c3a917c9bc2512f26905556f42ce0c781f26a63ecd9).
Since a transpose operation is being performed, you have to switch width with height when initialising the result array.
I opened a pull request for 240x135px LCD [here](https://github.com/pimoroni/st7789-python/pull/16), but it's the same.
